[package]
name = "cryn-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen-futures = "0.4.58"
web-sys = "0.3.85"
